lint: Add `FromStr` for `NodeAddress` (#2444)
Linting complained about `NodeAddress` implementing `TryFrom<&str>`
instead of `FromStr`:

```
error: `TryFrom<str>` could be `FromStr`
   --> redis/src/cluster_handling/mod.rs:76:1
    |
 76 | / impl TryFrom<&str> for NodeAddress {
 77 | |     type Error = RedisError;
 78 | |
 79 | |     fn try_from(s: &str) -> Result<Self, Self::Error> {
 ...  |
 83 | | }
    | |_^
```

See https://github.com/redis-rs/redis-rs/actions/runs/36986397736/job/110772560647?pr=2442#step:3:1263

So we add a `FromStr` implementation.

But we keep the `TryFrom<&str>` to stay backwards compatible.

fixes #2443