Introduce `pipeline.is_empty()` method to fix clippy warning
The following clippy warning is raised if the pipeline struct
does not contain an `is_empty()` method.

```
error: struct `Pipeline` has a public `len` method, but no `is_empty` method
  --> redis/src/pipeline.rs:93:5
   |
93 |     pub fn len(&self) -> usize {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#len_without_is_empty
   = note: `-D clippy::len-without-is-empty` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::len_without_is_empty)]`
```