fix: pin futures dependency to required version
fixes #515:
> error[E0432]: unresolved import `futures_util::Stream`

Signed-off-by: Sean Pianka <pianka@eml.cc>