Choose sleep function according to active runtime.
The current implementation caused the occasional error in async-std tests, where both tokio & async-std-comp features are turned on, and the default sleep is with tokio.

```
test cluster_async::test_async_cluster_basic_failover::case_2_async_std ... Panic: panicked at redis/src/cluster_async/mod.rs:231:21:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
Panic: panicked at redis/tests/test_cluster_async.rs:509:33:
redis_cluster: Unable to receive command
```